In [33]:
import pandas as pd
import random
import numpy as np
from datetime import datetime, timedelta
import ast
import math

In [65]:
signal_need_to_compare = pd.read_csv("need_to_compare_realtime.csv").head(1)["signal_code"].values[0]
summary_compare_realtime = pd.read_csv("summary_compare_realtime.csv")
detail_compare_realtime =  pd.read_csv("detail_compare_realtime.csv")

In [66]:
real_time = pd.read_csv(f"./Cassandra/{signal_need_to_compare}.csv")
# real_time = pd.read_csv("sd1_v0_eventrecord_eventrecord_traininformation_trainspeed.csv")
real_time

,unit_no,signal_code,time,frozen_times,int_value,numeric_value,string_value,times,timestamp_value
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:59.800,"[2024-07-09 10:00:01,2024-07-09 10:00:01,2024-...",1000,NaN,NaN,NaN,NaN
1,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:54.800,"[2024-07-09 09:59:55,2024-07-09 09:59:55,2024-...",1000,NaN,NaN,NaN,NaN
2,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:49.800,"[2024-07-09 09:59:50,2024-07-09 09:59:50,2024-...",1000,NaN,NaN,NaN,NaN
3,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:44.800,"[2024-07-09 09:59:45,2024-07-09 09:59:45,2024-...",1000,NaN,NaN,NaN,NaN
4,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:42.000,"[2024-07-09 09:59:42,2024-07-09 09:59:42,2024-...",1000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1572,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:19.600,"[2024-07-09 08:00:20,2024-07-09 08:00:20,2024-...",5380,NaN,NaN,NaN,NaN
1573,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:14.600,"[2024-07-09 08:00:14,2024-07-09 08:00:15,2024-...",5380,NaN,NaN,NaN,NaN
1574,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:09.600,"[2024-07-09 08:00:10,2024-07-09 08:00:10,2024-...",5380,NaN,NaN,NaN,NaN
1575,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:04.600,"[2024-07-09 08:00:04,2024-07-09 08:00:05,2024-...",5380,NaN,NaN,NaN,NaN
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:00.000,"[2024-07-09 08:00:00,2024-07-09 08:00:00,2024-...",5380,NaN,NaN,NaN,NaN

In [67]:
def convertColumnToArray(x):
    x = x.replace("[" , "").replace("]" , "")
    x = x.split(",")
    return x

real_time["frozen_times"] = real_time["frozen_times"].apply(convertColumnToArray)
real_time

,unit_no,signal_code,time,frozen_times,int_value,numeric_value,string_value,times,timestamp_value
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:59.800,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN
1,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:54.800,"[2024-07-09 09:59:55, 2024-07-09 09:59:55, 202...",1000,NaN,NaN,NaN,NaN
2,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:49.800,"[2024-07-09 09:59:50, 2024-07-09 09:59:50, 202...",1000,NaN,NaN,NaN,NaN
3,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:44.800,"[2024-07-09 09:59:45, 2024-07-09 09:59:45, 202...",1000,NaN,NaN,NaN,NaN
4,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:42.000,"[2024-07-09 09:59:42, 2024-07-09 09:59:42, 202...",1000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1572,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:19.600,"[2024-07-09 08:00:20, 2024-07-09 08:00:20, 202...",5380,NaN,NaN,NaN,NaN
1573,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:14.600,"[2024-07-09 08:00:14, 2024-07-09 08:00:15, 202...",5380,NaN,NaN,NaN,NaN
1574,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:09.600,"[2024-07-09 08:00:10, 2024-07-09 08:00:10, 202...",5380,NaN,NaN,NaN,NaN
1575,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:04.600,"[2024-07-09 08:00:04, 2024-07-09 08:00:05, 202...",5380,NaN,NaN,NaN,NaN
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:00.000,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN

In [68]:
def seperateTime(x):
    if x[3][0] == "" :
        return [x[2]]
    else:
        parse_frozen_time = x[3].copy()
        parse_frozen_time.insert(0 , x[2])
        current_second = int(parse_frozen_time[0].split(" ")[1].split(":")[2].split(".")[0])
        current_milisecond = int(parse_frozen_time[0].split(" ")[1].split(".")[1])
        for i in range(len(parse_frozen_time)):
            if i == 0 :
                continue
            elif i == len(parse_frozen_time) - 1:
                if int(parse_frozen_time[i].split(" ")[1].split(":")[2].split(".")[0]) == current_second :
                    milisecond = int(int(current_milisecond) + 200)
                    parse_frozen_time[i] = f'{parse_frozen_time[i].split(".")[0]}.{milisecond}'
                    current_milisecond = int(parse_frozen_time[i].split(" ")[1].split(".")[1])
                else:
                    parse_frozen_time[i] = f'{parse_frozen_time[i].split(".")[0]}.000'
            else:
                if int(parse_frozen_time[i].split(" ")[1].split(":")[2].split(".")[0]) == current_second :
                    milisecond = int(int(current_milisecond) + 200)
                    parse_frozen_time[i] = f'{parse_frozen_time[i].split(".")[0]}.{milisecond}'
                    current_milisecond = int(parse_frozen_time[i].split(" ")[1].split(".")[1])
                else:
                        parse_frozen_time[i] = f'{parse_frozen_time[i].split(".")[0]}.000'
                        current_second = int(parse_frozen_time[i].split(" ")[1].split(":")[2].split(".")[0])
                        current_milisecond = 0
        return parse_frozen_time
real_time["parse_frozen_time"]=real_time.apply(seperateTime , axis = 1)
real_time

C:\Users\khangnguyen1\AppData\Local\Temp\ipykernel_5472\20941865.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if x[3][0] == "" :
C:\Users\khangnguyen1\AppData\Local\Temp\ipykernel_5472\20941865.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  parse_frozen_time = x[3].copy()
C:\Users\khangnguyen1\AppData\Local\Temp\ipykernel_5472\20941865.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  parse_frozen_time.insert(0 , x[2])
C:\Users\khangnguyen1\AppData\Local\Temp\ipykernel_5472\20941865.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return [x[2]]

,unit_no,signal_code,time,frozen_times,int_value,numeric_value,string_value,times,timestamp_value,parse_frozen_time
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:59.800,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,"[2024-07-09 09:59:59.800, 2024-07-09 10:00:01...."
1,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:54.800,"[2024-07-09 09:59:55, 2024-07-09 09:59:55, 202...",1000,NaN,NaN,NaN,NaN,"[2024-07-09 09:59:54.800, 2024-07-09 09:59:55...."
2,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:49.800,"[2024-07-09 09:59:50, 2024-07-09 09:59:50, 202...",1000,NaN,NaN,NaN,NaN,"[2024-07-09 09:59:49.800, 2024-07-09 09:59:50...."
3,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:44.800,"[2024-07-09 09:59:45, 2024-07-09 09:59:45, 202...",1000,NaN,NaN,NaN,NaN,"[2024-07-09 09:59:44.800, 2024-07-09 09:59:45...."
4,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:42.000,"[2024-07-09 09:59:42, 2024-07-09 09:59:42, 202...",1000,NaN,NaN,NaN,NaN,"[2024-07-09 09:59:42.000, 2024-07-09 09:59:42...."
...,...,...,...,...,...,...,...,...,...,...
1572,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:19.600,"[2024-07-09 08:00:20, 2024-07-09 08:00:20, 202...",5380,NaN,NaN,NaN,NaN,"[2024-07-09 08:00:19.600, 2024-07-09 08:00:20...."
1573,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:14.600,"[2024-07-09 08:00:14, 2024-07-09 08:00:15, 202...",5380,NaN,NaN,NaN,NaN,"[2024-07-09 08:00:14.600, 2024-07-09 08:00:14...."
1574,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:09.600,"[2024-07-09 08:00:10, 2024-07-09 08:00:10, 202...",5380,NaN,NaN,NaN,NaN,"[2024-07-09 08:00:09.600, 2024-07-09 08:00:10...."
1575,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:04.600,"[2024-07-09 08:00:04, 2024-07-09 08:00:05, 202...",5380,NaN,NaN,NaN,NaN,"[2024-07-09 08:00:04.600, 2024-07-09 08:00:04...."
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:00.000,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,"[2024-07-09 08:00:00.000, 2024-07-09 08:00:00...."

In [69]:
real_time.explode('parse_frozen_time').to_csv("compare-realtime.csv")

In [70]:
batch = pd.read_csv('./datasese/datagw.csv')
# batch = pd.read_csv('query-impala-24414.csv')
batch

C:\Users\khangnguyen1\AppData\Local\Temp\ipykernel_5472\1810607265.py:1: DtypeWarning: Columns (73,77,110,627,790,874,887) have mixed types. Specify dtype option on import or set low_memory=False.
  batch = pd.read_csv('./datasese/datagw.csv')

,filename,pentahocounter,calendar_timestamp,sd1_v0_headerinformation_destinationdeviceid,sd1_v0_headerinformation_datalength,YearHCode,YearLCode,MonthHCode,MonthLCode,DayHCode,...,sd1_v12_otmr_otmr_vehicleid12_odometer,sd1_v0_ethernetapplication_commondataofsdr_csvsdr1_commondatatraininformation1_speedlimiterinformation_speedlimitactive,sd1_v0_ethernetapplication_commondataofsdr_csvsdr1_commondatatraininformation1_speedlimiterinformation_constantspeedpowering,sd1_v0_ethernetapplication_commondataofsdr_csvsdr1_commondatatraininformation1_speedlimiterinformation_constantspeedbraking,sd1_v0_ethernetapplication_commondataofsdr_csvsdr1_speedlimit_trainspeeddifference,sd1_v0_ethernetapplication_commondataofsdr_csvsdr1_speedlimit_tractiveeffort,sd1_v0_ethernetapplication_commondataofsdr_csvsdr1_speedlimit_brakeeffort,Year,Month,Day
0,SD2407090615141-800030-SD1,0,2024-07-09 06:15:13.000000000,78,1328,2,4,0,7,0,...,1,0,NaN,NaN,0.0,NaN,NaN,2024,7,9
1,SD2407090615141-800030-SD1,1,2024-07-09 06:15:13.200000000,78,1328,2,4,0,7,0,...,1,0,NaN,NaN,0.0,NaN,NaN,2024,7,9
2,SD2407090615141-800030-SD1,2,2024-07-09 06:15:13.400000000,78,1328,2,4,0,7,0,...,1,0,NaN,NaN,0.0,NaN,NaN,2024,7,9
3,SD2407090615141-800030-SD1,3,2024-07-09 06:15:13.600000000,78,1328,2,4,0,7,0,...,1,0,NaN,NaN,0.0,NaN,NaN,2024,7,9
4,SD2407090615141-800030-SD1,4,2024-07-09 06:15:13.800000000,78,1328,2,4,0,7,0,...,1,0,NaN,NaN,0.0,NaN,NaN,2024,7,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71895,SD2407090615141-800030-SD1,35896,2024-07-09 08:14:23.400000000,78,1328,2,4,0,7,0,...,0,0,NaN,NaN,0.0,NaN,NaN,2024,7,9
71896,SD2407090615141-800030-SD1,35897,2024-07-09 08:14:23.600000000,78,1328,2,4,0,7,0,...,0,0,NaN,NaN,0.0,NaN,NaN,2024,7,9
71897,SD2407090615141-800030-SD1,35898,2024-07-09 08:14:23.800000000,78,1328,2,4,0,7,0,...,0,0,NaN,NaN,0.0,NaN,NaN,2024,7,9
71898,SD2407090615141-800030-SD1,35899,2024-07-09 08:14:24.000000000,78,1328,2,4,0,7,0,...,0,0,NaN,NaN,0.0,NaN,NaN,2024,7,9
71899,SD2407090615141-800030-SD1,35900,2024-07-09 08:14:24.200000000,78,1328,2,4,0,7,0,...,0,0,NaN,NaN,0.0,NaN,NaN,2024,7,9

In [410]:
current_second_batch = int(batch.iloc[0,2].split(" ")[1].split(":")[2].split(".")[0])
current_milisecond_batch = int(batch.iloc[0,2].split(" ")[1].split(".")[1])
for i in range(len(batch)):
            if i == 0 :
                continue
            else:
                if int(batch.iloc[i,2].split(" ")[1].split(":")[2].split(".")[0]) == current_second_batch :
                    milisecond_batch = int(int(current_milisecond_batch) + 200)
                    batch.iloc[i,2] = f'{batch.iloc[i,2].split(".")[0]}.{milisecond_batch}'
                    current_milisecond_batch =  int(batch.iloc[i,2].split(" ")[1].split(".")[1])
                else:
                        current_second_batch = int(batch.iloc[i,2].split(" ")[1].split(":")[2].split(".")[0])
                        current_milisecond_batch = 0

batch

AttributeError: 'numpy.float64' object has no attribute 'split'

In [71]:
real_time = real_time.explode("parse_frozen_time")
real_time

,unit_no,signal_code,time,frozen_times,int_value,numeric_value,string_value,times,timestamp_value,parse_frozen_time
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:59.800,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 09:59:59.800
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:59.800,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:01.000
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:59.800,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:01.200
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:59.800,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:01.400
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 09:59:59.800,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:01.600
...,...,...,...,...,...,...,...,...,...,...
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:00.000,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:03.400
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:00.000,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:03.600
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:00.000,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:04.000
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:00.000,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:04.200
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,2024-07-09 08:00:00.000,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:04.400

In [72]:
real_time = real_time.drop(columns=['time']) 
real_time

,unit_no,signal_code,frozen_times,int_value,numeric_value,string_value,times,timestamp_value,parse_frozen_time
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 09:59:59.800
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:01.000
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:01.200
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:01.400
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:01.600
...,...,...,...,...,...,...,...,...,...
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:03.400
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:03.600
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:04.000
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:04.200
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:04.400

In [73]:
real_time = real_time.sort_values(by=['parse_frozen_time'])
real_time

,unit_no,signal_code,frozen_times,int_value,numeric_value,string_value,times,timestamp_value,parse_frozen_time
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:00.000
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:00.200
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:00.400
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:00.600
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,NaN,NaN,NaN,NaN,2024-07-09 08:00:00.800
...,...,...,...,...,...,...,...,...,...
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:02.000
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:02.200
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:02.400
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:02.600
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,NaN,NaN,NaN,NaN,2024-07-09 10:00:02.800

In [74]:
batch = batch[["filename" , "pentahocounter" ,"calendar_timestamp" ,f"{signal_need_to_compare}"]]
batch

,filename,pentahocounter,calendar_timestamp,sd1_v0_eventrecord_eventrecord_traininformation_startingstationid
0,SD2407090615141-800030-SD1,0,2024-07-09 06:15:13.000000000,5380
1,SD2407090615141-800030-SD1,1,2024-07-09 06:15:13.200000000,5380
2,SD2407090615141-800030-SD1,2,2024-07-09 06:15:13.400000000,5380
3,SD2407090615141-800030-SD1,3,2024-07-09 06:15:13.600000000,5380
4,SD2407090615141-800030-SD1,4,2024-07-09 06:15:13.800000000,5380
...,...,...,...,...
71895,SD2407090615141-800030-SD1,35896,2024-07-09 08:14:23.400000000,5380
71896,SD2407090615141-800030-SD1,35897,2024-07-09 08:14:23.600000000,5380
71897,SD2407090615141-800030-SD1,35898,2024-07-09 08:14:23.800000000,5380
71898,SD2407090615141-800030-SD1,35899,2024-07-09 08:14:24.000000000,5380
71899,SD2407090615141-800030-SD1,35900,2024-07-09 08:14:24.200000000,5380

In [75]:
batch["calendar_timestamp"] = pd.to_datetime(batch["calendar_timestamp"])

C:\Users\khangnguyen1\AppData\Local\Temp\ipykernel_5472\2972911169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch["calendar_timestamp"] = pd.to_datetime(batch["calendar_timestamp"])

In [76]:
batch = batch[(batch["calendar_timestamp"] >= '2024-07-09 07:00:00.000') &  (batch["calendar_timestamp"] <= '2024-07-09 09:00:00.000')]
batch

,filename,pentahocounter,calendar_timestamp,sd1_v0_eventrecord_eventrecord_traininformation_startingstationid
2005,SD2407090814551-800030-SD1,0,2024-07-09 08:14:53.000,5380
2006,SD2407090814551-800030-SD1,1,2024-07-09 08:14:53.200,5380
2007,SD2407090814551-800030-SD1,2,2024-07-09 08:14:54.000,5380
2008,SD2407090814551-800030-SD1,3,2024-07-09 08:14:54.200,5380
2009,SD2407090814551-800030-SD1,4,2024-07-09 08:14:54.400,5380
...,...,...,...,...
71895,SD2407090615141-800030-SD1,35896,2024-07-09 08:14:23.400,5380
71896,SD2407090615141-800030-SD1,35897,2024-07-09 08:14:23.600,5380
71897,SD2407090615141-800030-SD1,35898,2024-07-09 08:14:23.800,5380
71898,SD2407090615141-800030-SD1,35899,2024-07-09 08:14:24.000,5380
71899,SD2407090615141-800030-SD1,35900,2024-07-09 08:14:24.200,5380

In [77]:
signal_value_type = ""
list_signal_Type = ["int_value" , "numeric_value" , "string_value" , "times" , "timestamp_value"]
if str(real_time.head(1)["int_value"].values[0]) != "nan":
    signal_value_type = "int_value"
elif str(real_time.head(1)["numeric_value"].values[0]) != "nan":
    signal_value_type = "numeric_value"
elif str(real_time.head(1)["string_value"].values[0]) != "nan":
    signal_value_type = "string_value"
elif str(real_time.head(1)["times"].values[0]) != "nan":
    signal_value_type = "times"
else : 
    signal_value_type = "timestamp_value"
list_signal_Type = [i for i in list_signal_Type if i != signal_value_type]
list_signal_Type

['numeric_value', 'string_value', 'times', 'timestamp_value']

In [78]:
real_time = real_time.drop(columns=list_signal_Type)
real_time

,unit_no,signal_code,frozen_times,int_value,parse_frozen_time
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.000
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.200
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.400
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.600
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.800
...,...,...,...,...,...
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.000
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.200
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.400
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.600
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.800

In [79]:
real_time

,unit_no,signal_code,frozen_times,int_value,parse_frozen_time
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.000
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.200
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.400
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.600
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.800
...,...,...,...,...,...
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.000
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.200
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.400
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.600
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.800

In [80]:
real_time["parse_frozen_time"] = pd.to_datetime(real_time["parse_frozen_time"])
real_time

,unit_no,signal_code,frozen_times,int_value,parse_frozen_time
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.000
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.200
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.400
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.600
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 08:00:00.800
...,...,...,...,...,...
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.000
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.200
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.400
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.600
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 10:00:02.800

In [81]:
real_time["parse_frozen_time"] = real_time["parse_frozen_time"] + pd.Timedelta(hours = 1)

In [82]:
real_time.columns = ["unit_no" ,"signal_code","frozen_times","numeric_value" , "calendar_timestamp"]
real_time

,unit_no,signal_code,frozen_times,numeric_value,calendar_timestamp
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.000
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.200
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.400
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.600
1576,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.800
...,...,...,...,...,...
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.000
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.200
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.400
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.600
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.800

In [83]:
real_time.reset_index(inplace = True,drop=True)
# real_time = real_time.drop(columns = ["index"])
real_time

,unit_no,signal_code,frozen_times,numeric_value,calendar_timestamp
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.000
1,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.200
2,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.400
3,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.600
4,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.800
...,...,...,...,...,...
35064,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.000
35065,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.200
35066,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.400
35067,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.600
35068,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.800

In [84]:
real_time_clean = []
for it in range(len(real_time)):
    if "1" not in str(real_time.iloc[it , 4].microsecond):
            real_time_clean.append(real_time.iloc[it])

In [85]:
real_time_clean = pd.DataFrame(real_time_clean)
real_time_clean

,unit_no,signal_code,frozen_times,numeric_value,calendar_timestamp
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.000
1,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.200
2,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.400
3,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.600
4,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.800
...,...,...,...,...,...
35064,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.000
35065,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.200
35066,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.400
35067,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.600
35068,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.800

In [86]:
compare = real_time_clean.merge(batch ,how = 'left' , on =['calendar_timestamp'])
compare

,unit_no,signal_code,frozen_times,numeric_value,calendar_timestamp,filename,pentahocounter,sd1_v0_eventrecord_eventrecord_traininformation_startingstationid
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.000,NaN,NaN,NaN
1,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.200,NaN,NaN,NaN
2,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.400,NaN,NaN,NaN
3,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.600,NaN,NaN,NaN
4,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.800,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
34259,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.000,NaN,NaN,NaN
34260,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.200,NaN,NaN,NaN
34261,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.400,NaN,NaN,NaN
34262,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.600,NaN,NaN,NaN
34263,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.800,NaN,NaN,NaN

In [87]:
compare[compare[f"{signal_need_to_compare}"].isna()]
# compare[compare["sd1_v0_eventrecord_eventrecord_traininformation_trainspeed"].isna()]

,unit_no,signal_code,frozen_times,numeric_value,calendar_timestamp,filename,pentahocounter,sd1_v0_eventrecord_eventrecord_traininformation_startingstationid
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.000,NaN,NaN,NaN
1,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.200,NaN,NaN,NaN
2,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.400,NaN,NaN,NaN
3,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.600,NaN,NaN,NaN
4,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.800,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
34259,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.000,NaN,NaN,NaN
34260,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.200,NaN,NaN,NaN
34261,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.400,NaN,NaN,NaN
34262,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.600,NaN,NaN,NaN
34263,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.800,NaN,NaN,NaN

In [88]:
list_result = []  
for e in range(len(compare)):
    if signal_value_type == "int_value" or signal_value_type == "numeric_value" : 
        if float(compare.iloc[e , 3]) != float(compare.iloc[e , 7]):
                list_result.append(compare.iloc[e])
    else:
        if str(compare.iloc[e , 3]) != str(compare.iloc[e , 7]):
                list_result.append(compare.iloc[e])


# list_result = []  
# for e in range(len(compare)):
#     if signal_value_type == "int_value" or signal_value_type == "numeric_value" : 
#         if float(compare.iloc[e , 3]) != float(compare.iloc[e , 6]):
#                 list_result.append(compare.iloc[e])
#     else:
#         if str(compare.iloc[e , 3]) != str(compare.iloc[e , 6]):
#                 list_result.append(compare.iloc[e])

In [89]:
result = pd.DataFrame(list_result)
result.columns = ["unit_no" , "signal_code" , "frozen_times" , "realtime_value" , "calendar_timestamp" , "filename" , "pentahocounter" , "batch_value"]
result

,unit_no,signal_code,frozen_times,realtime_value,calendar_timestamp,filename,pentahocounter,batch_value
0,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.000,NaN,NaN,NaN
1,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.200,NaN,NaN,NaN
2,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.400,NaN,NaN,NaN
3,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.600,NaN,NaN,NaN
4,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 08:00:00, 2024-07-09 08:00:00, 202...",5380,2024-07-09 09:00:00.800,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
34259,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.000,NaN,NaN,NaN
34260,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.200,NaN,NaN,NaN
34261,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.400,NaN,NaN,NaN
34262,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.600,NaN,NaN,NaN
34263,800030,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-07-09 10:00:01, 2024-07-09 10:00:01, 202...",1000,2024-07-09 11:00:02.800,NaN,NaN,NaN

In [90]:
summary = pd.DataFrame([[f'{signal_need_to_compare}' , len(result), len(real_time_clean)]] , columns = ["signal_code" , "number_column_mismatch" , "total_rows"])
summary

,signal_code,number_column_mismatch,total_rows
0,sd1_v0_eventrecord_eventrecord_traininformatio...,34264,34264

In [91]:
pd.concat([summary_compare_realtime, summary], ignore_index=True).to_csv("summary_compare_realtime.csv" , index = False)
pd.concat([detail_compare_realtime, result], ignore_index=True).to_csv("detail_compare_realtime.csv" , index = False)
if(len(summary) > 0 ):
    pd.read_csv("need_to_compare_realtime.csv").drop(0).to_csv("need_to_compare_realtime.csv" ,  index = False)

C:\Users\khangnguyen1\AppData\Local\Temp\ipykernel_5472\2316351057.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat([detail_compare_realtime, result], ignore_index=True).to_csv("detail_compare_realtime.csv" , index = False)

In [233]:
# summary_compare_realtime

In [234]:
# detail_compare_realtime

In [437]:
result.to_csv("export_compare.csv" , index = False)

In [431]:
# batch[batch["pentahocounter"] == 3218]

In [432]:
# batch[batch["calendar_timestamp"] >= "2024-06-10 08:29:05.800"].head(30)

In [61]:
real_time.dtypes

unit_no                        int64
signal_code                   object
frozen_times                  object
numeric_value                  int64
calendar_timestamp    datetime64[ns]
dtype: object

In [433]:
# test = ['sd1_v0_counter','sd1_v0_eventrecord_carnumber_tmscarnumber','sd1_v0_eventrecord_carnumber_uniquecarnumber','sd1_v0_eventrecord_carnumber_unitnumber','sd1_v0_eventrecord_dateofeventoccurred_dayh','sd1_v0_eventrecord_dateofeventoccurred_dayl','sd1_v0_eventrecord_dateofeventoccurred_hourh','sd1_v0_eventrecord_dateofeventoccurred_hourl','sd1_v0_eventrecord_dateofeventoccurred_minuteh','sd1_v0_eventrecord_dateofeventoccurred_minutel','sd1_v0_eventrecord_dateofeventoccurred_monthh','sd1_v0_eventrecord_dateofeventoccurred_monthl','sd1_v0_eventrecord_dateofeventoccurred_secondh','sd1_v0_eventrecord_dateofeventoccurred_secondl','sd1_v0_eventrecord_dateofeventoccurred_yearh','sd1_v0_eventrecord_dateofeventoccurred_yearl','sd1_v0_eventrecord_decouplingcoupling','sd1_v0_eventrecord_failurecode','sd1_v0_eventrecord_gpslocation_directionoflatitude','sd1_v0_eventrecord_gpslocation_directionoflongitude','sd1_v0_eventrecord_gpslocation_latitudedegrees','sd1_v0_eventrecord_gpslocation_latitudeminutes','sd1_v0_eventrecord_gpslocation_longitudedegrees','sd1_v0_eventrecord_gpslocation_longitudeminutes','sd1_v0_eventrecord_notchinformaion_notch','sd1_v0_eventrecord_occurrencerecovering','sd1_v0_eventrecord_overheadlinevoltage_overheadlinevoltageac','sd1_v0_eventrecord_overheadlinevoltage_overheadlinevoltagedc','sd1_v0_eventrecord_runningsectioncode_nextstationcode','sd1_v0_eventrecord_runningsectioncode_relevantstationcode','sd1_v0_eventrecord_speed_speed','sd1_v0_eventrecord_trackmode_acctr','sd1_v0_eventrecord_trackmode_acnl','sd1_v0_eventrecord_trackmode_dcnl','sd1_v0_screendisplaydata_loginstatus_anotherunitdpt1loginstatus','sd1_v0_screendisplaydata_loginstatus_anotherunitdpt2loginstatus','sd1_v0_screendisplaydata_loginstatus_selfunitdpt1loginstatus','sd1_v0_screendisplaydata_loginstatus_selfunitdpt2loginstatus','sd1_v0_screendisplaydata_nextstationcode_nextstationcode','sd1_v0_screendisplaydata_unitstatus_couplingstatus','sd1_v0_statisticaldata_compressor_compoperatinghoursdpt1_operatinghours','sd1_v0_statisticaldata_compressor_compoperatinghoursdpt2_operatinghours','sd1_v0_statisticaldata_mileage_odometerrunningdistance','sd1_v0_unitnumber','sd1_v1_bcu_bcutransmission_analogdata7_bsrpressure','sd1_v1_bcu_bcutransmission_brakefault_bcumajorfault','sd1_v1_bcu_bcutransmission_brakefault_dumpvaluefault1','sd1_v1_bcu_bcutransmission_brakefault_dumpvaluefault2','sd1_v1_bcu_bcutransmission_brakefault_dumpvaluefault3','sd1_v1_bcu_bcutransmission_brakefault_dumpvaluefault4','sd1_v1_bcu_bcutransmission_brakefault_lockedaxle1','sd1_v1_bcu_bcutransmission_brakefault_lockedaxle2','sd1_v1_bcu_bcutransmission_brakefault_lockedaxle3','sd1_v1_bcu_bcutransmission_brakefault_lockedaxle4','sd1_v1_bcu_bcutransmission_brakefault_sandrequestrefused','sd1_v1_bcu_bcutransmission_brakefault_speedsensorfault1','sd1_v1_bcu_bcutransmission_brakefault_speedsensorfault2','sd1_v1_bcu_bcutransmission_brakefault_speedsensorfault3','sd1_v1_bcu_bcutransmission_brakefault_speedsensorfault4','sd1_v1_bcu_bcutransmission_brakefault_wspmajorfault','sd1_v1_bcu_bcutransmission_brakefault_wsptimeout1','sd1_v1_bcu_bcutransmission_brakefault_wsptimeout2','sd1_v1_bcu_bcutransmission_brakefault_wsptimeout3','sd1_v1_bcu_bcutransmission_brakefault_wsptimeout4','sd1_v1_bcu_bcutransmission_brakestatus_sanding','sd1_v1_bcu_bcutransmission_tmscarnumber_tmscarnumber','sd1_v1_dido_dido_fsdi_doorclosecommandleft','sd1_v1_dido_dido_fsdi_doorclosecommandright','sd1_v1_dido_dido_fsdi_dooropencommandleft','sd1_v1_dido_dido_fsdi_dooropencommandright','sd1_v1_dido_dido_fsdi_doorreleaseleft','sd1_v1_dido_dido_fsdi_doorreleaseright','sd1_v1_dido_dido_fsdi_forwardmodeline','sd1_v1_dido_dido_fsdi_reversemodeline','sd1_v1_dido_dido_fsdi_speedsignalmorethan25kmh','sd1_v1_dido_dido_fsdi_speedsignalmorethan5kmh','sd1_v1_dido_dido_monitoringdi110v_ddson','sd1_v1_dido_dido_monitoringdi110v_emergencypantographup','sd1_v1_dido_dido_monitoringdi110v_otmrfailure','sd1_v1_dido_dido_monitoringdi110v_pantographdownshoeupsw','sd1_v1_dido_dido_monitoringdi110v_pantographupshoedownsw','sd1_v1_dido_dido_monitoringdi110v_powersupplyforaxletemperaturedetectioncircuit','sd1_v1_dido_dido_monitoringdi110v_powersupplyforbrake','sd1_v1_dido_dido_monitoringdi110v_powersupplyfordriversdisplayunit','sd1_v1_dido_dido_monitoringdi110v_powersupplyforhvac','sd1_v1_dido_dido_monitoringdi110v_powersupplyforotmr','sd1_v1_dido_dido_monitoringdi110v_powersupplyforpis','sd1_v1_dido_dido_monitoringdi110v_speedindicatorfailure','sd1_v1_dido_dido_monitoringdi110v_uncouplingsw','sd1_v1_dido_dido_monitoringdi24v_acpowersupplyisovercurrentacocrstatus','sd1_v1_dido_dido_monitoringdi24v_airsuspensionpressuredown','sd1_v1_dido_dido_monitoringdi24v_anyotherareadetectionisisolated','sd1_v1_dido_dido_monitoringdi24v_auxliarycompressorisinoperation','sd1_v1_dido_dido_monitoringdi24v_brakecockisbeingblocked','sd1_v1_dido_dido_monitoringdi24v_brakeisdragging','sd1_v1_dido_dido_monitoringdi24v_cabareafire','sd1_v1_dido_dido_monitoringdi24v_cabdooropenleft','sd1_v1_dido_dido_monitoringdi24v_cabdooropenright','sd1_v1_dido_dido_monitoringdi24v_compressorfailure','sd1_v1_dido_dido_monitoringdi24v_ebrstatus','sd1_v1_dido_dido_monitoringdi24v_emergencydoorhandle1','sd1_v1_dido_dido_monitoringdi24v_emergencydoorhandle2','sd1_v1_dido_dido_monitoringdi24v_emergencydoorhandle3','sd1_v1_dido_dido_monitoringdi24v_emergencydoorhandle4','sd1_v1_dido_dido_monitoringdi24v_failureofbatterybackupunitforreservelamp1','sd1_v1_dido_dido_monitoringdi24v_failureofbrake','sd1_v1_dido_dido_monitoringdi24v_failureofcabhvac','sd1_v1_dido_dido_monitoringdi24v_failureofgangwaydoor','sd1_v1_dido_dido_monitoringdi24v_firedetectionsystemfailure','sd1_v1_dido_dido_monitoringdi24v_hotaxlebearingdetection11','sd1_v1_dido_dido_monitoringdi24v_hotaxlebearingdetection12','sd1_v1_dido_dido_monitoringdi24v_hotaxlebearingdetection13','sd1_v1_dido_dido_monitoringdi24v_hotaxlebearingdetection14','sd1_v1_dido_dido_monitoringdi24v_hotaxlebearingdetection21','sd1_v1_dido_dido_monitoringdi24v_hotaxlebearingdetection22','sd1_v1_dido_dido_monitoringdi24v_hotaxlebearingdetection23','sd1_v1_dido_dido_monitoringdi24v_hotaxlebearingdetection24','sd1_v1_dido_dido_monitoringdi24v_kvbemergencybrake','sd1_v1_dido_dido_monitoringdi24v_pantographautomaticdowndetection','sd1_v1_dido_dido_monitoringdi24v_pantographstatus','sd1_v1_dido_dido_monitoringdi24v_powersupplyforavacuumequipmentfortoiletsystem','sd1_v1_dido_dido_monitoringdi24v_saloonareafire','sd1_v1_dido_dido_monitoringdi24v_sandingcockisbeingblocked','sd1_v1_dido_dido_monitoringdi24v_toiletareafire','sd1_v1_dido_dido_monitoringdi24v_tpwsawsemergencybrake','sd1_v1_dido_dido_monitoringdi24v_tractionabnormaldetectionfunctionisfailed','sd1_v1_dido_dido_monitoringdi24v_tractionareafire','sd1_v1_dido_dido_monitoringdi24v_tractionarealdetectionfunctionisisolated','sd1_v1_dido_dido_monitoringdi24v_tvm430emergencybrake','sd1_v1_dido_dido_monitoringdo_powersupplyforbuzzerfordriversdispalyunit','sd1_v1_hvac_hvactransmission_airconditioningequipmentmonitorinformation9_cabtemperature','sd1_v1_otmr_otmrtransmission_brake_brakecylinderpressuredpts1','sd1_v1_otmr_otmrtransmission_brake_brakecylinderpressuredpts2','sd1_v1_otmr_otmrtransmission_brake_brakecylinderpressurems1','sd1_v1_otmr_otmrtransmission_brake_brakecylinderpressurems2','sd1_v1_otmr_otmrtransmission_brake_brakecylinderpressurems3','sd1_v1_otmr_otmrtransmission_brake_brakecylinderpressurems4','sd1_v1_otmr_otmrtransmission_brake_brakereservoirpressuredpts1','sd1_v1_otmr_otmrtransmission_brake_brakereservoirpressuredpts2','sd1_v1_otmr_otmrtransmission_brake_brakereservoirpressurems1','sd1_v1_otmr_otmrtransmission_brake_brakereservoirpressurems2','sd1_v1_otmr_otmrtransmission_brake_brakereservoirpressurems3','sd1_v1_otmr_otmrtransmission_brake_brakereservoirpressurems4','sd1_v1_otmr_otmrtransmission_brake_wspactivedpts1','sd1_v1_otmr_otmrtransmission_brake_wspactivedpts2','sd1_v1_otmr_otmrtransmission_brake_wspactivems1','sd1_v1_otmr_otmrtransmission_brake_wspactivems2','sd1_v1_otmr_otmrtransmission_brake_wspactivems3','sd1_v1_otmr_otmrtransmission_brake_wspactivems4','sd1_v1_otmr_otmrtransmission_couple_cabcoupled','sd1_v1_otmr_otmrtransmission_couple_couplecoverswitch','sd1_v1_otmr_otmrtransmission_couple_couplepushbutton','sd1_v1_otmr_otmrtransmission_couple_uncouplepushbutton','sd1_v1_otmr_otmrtransmission_door_dirinformation1','sd1_v1_otmr_otmrtransmission_door_dirinformation12','sd1_v1_otmr_otmrtransmission_door_dirinformation6','sd1_v1_otmr_otmrtransmission_door_dirinformation7','sd1_v1_otmr_otmrtransmission_lineinformation_ctrlacselectbutton','sd1_v1_otmr_otmrtransmission_lineinformation_nracselectbutton','sd1_v1_otmr_otmrtransmission_lineinformation_nrdcselectbutton','sd1_v1_otmr_otmrtransmission_pea_peaoperationdpts1','sd1_v1_otmr_otmrtransmission_pea_peaoperationdpts2','sd1_v1_otmr_otmrtransmission_pea_peaoperationms1','sd1_v1_otmr_otmrtransmission_pea_peaoperationms2','sd1_v1_otmr_otmrtransmission_pea_peaoperationms3','sd1_v1_otmr_otmrtransmission_pea_peaoperationms4','sd1_v1_otmr_otmrtransmission_pinnumber_pinnumber','sd1_v1_otmr_otmrtransmission_sanding_sandercontroldpst1','sd1_v1_otmr_otmrtransmission_sanding_sandercontroldpts2','sd1_v1_otmr_otmrtransmission_sanding_sandercontrolms1','sd1_v1_otmr_otmrtransmission_sanding_sandercontrolms2','sd1_v1_otmr_otmrtransmission_sanding_sandercontrolms3','sd1_v1_otmr_otmrtransmission_sanding_sandercontrolms4','sd1_v1_otmr_otmrtransmission_sanding_sandrequestrefuseddpst1','sd1_v1_otmr_otmrtransmission_sanding_sandrequestrefuseddpts2','sd1_v1_otmr_otmrtransmission_sanding_sandrequestrefusedms1','sd1_v1_otmr_otmrtransmission_sanding_sandrequestrefusedms2','sd1_v1_otmr_otmrtransmission_sanding_sandrequestrefusedms3','sd1_v1_otmr_otmrtransmission_sanding_sandrequestrefusedms4','sd1_v1_otmr_otmrtransmission_sdo_emergencyreleaseoperation','sd1_v1_otmr_otmrtransmission_sdo_leftsidedoorsrelease','sd1_v1_otmr_otmrtransmission_sdo_rightsidedoorsrelease','sd1_v1_otmr_otmrtransmission_sdo_sdocommand1','sd1_v1_otmr_otmrtransmission_sdo_sdocommand10','sd1_v1_otmr_otmrtransmission_sdo_sdocommand11','sd1_v1_otmr_otmrtransmission_sdo_sdocommand12','sd1_v1_otmr_otmrtransmission_sdo_sdocommand2','sd1_v1_otmr_otmrtransmission_sdo_sdocommand3','sd1_v1_otmr_otmrtransmission_sdo_sdocommand4','sd1_v1_otmr_otmrtransmission_sdo_sdocommand5','sd1_v1_otmr_otmrtransmission_sdo_sdocommand6','sd1_v1_otmr_otmrtransmission_sdo_sdocommand7','sd1_v1_otmr_otmrtransmission_sdo_sdocommand8','sd1_v1_otmr_otmrtransmission_sdo_sdocommand9','sd1_v1_otmr_otmrtransmission_sdo_sdodoorreleaseerror','sd1_v1_otmr_otmrtransmission_sdo_stationchanged','sd1_v1_otmr_otmrtransmission_sdo_tmssdofault1','sd1_v1_otmr_otmrtransmission_sdo_tmssdofault2','sd1_v1_otmr_otmrtransmission_speedset_speedsetactive','sd1_v1_otmr_otmrtransmission_speedset_speedsetspeed','sd1_v1_otmr_otmrtransmission_speedset_tractionactiveforspeedset','sd1_v1_otmr_otmrtransmission_traction_icemodems1','sd1_v1_otmr_otmrtransmission_traction_icemodems2','sd1_v1_otmr_otmrtransmission_traction_icemodems3','sd1_v1_otmr_otmrtransmission_traction_icemodems4','sd1_v1_otmr_otmrtransmission_traction_poweringmodems1','sd1_v1_otmr_otmrtransmission_traction_poweringmodems2','sd1_v1_otmr_otmrtransmission_traction_poweringmodems3','sd1_v1_otmr_otmrtransmission_traction_poweringmodems4','sd1_v1_otmr_otmrtransmission_traction_powerredistributionmodems1','sd1_v1_otmr_otmrtransmission_traction_powerredistributionmodems2','sd1_v1_otmr_otmrtransmission_traction_powerredistributionmodems3','sd1_v1_otmr_otmrtransmission_traction_powerredistributionmodems4','sd1_v1_otmr_otmrtransmission_traction_slowspeedmodems1','sd1_v1_otmr_otmrtransmission_traction_slowspeedmodems2','sd1_v1_otmr_otmrtransmission_traction_slowspeedmodems3','sd1_v1_otmr_otmrtransmission_traction_slowspeedmodems4','sd1_v1_otmr_otmrtransmission_traction_tractionfaultms1','sd1_v1_otmr_otmrtransmission_traction_tractionfaultms2','sd1_v1_otmr_otmrtransmission_traction_tractionfaultms3','sd1_v1_otmr_otmrtransmission_traction_tractionfaultms4','sd1_v1_otmr_otmrtransmission_traction_tractionwspdetectedms1','sd1_v1_otmr_otmrtransmission_traction_tractionwspdetectedms2','sd1_v1_otmr_otmrtransmission_traction_tractionwspdetectedms3','sd1_v1_otmr_otmrtransmission_traction_tractionwspdetectedms4','sd1_v1_otmr_otmrtransmission_vcb_vcb1','sd1_v1_otmr_otmrtransmission_vcb_vcb2','sd1_v1_pis_pistransmission_gpsfault_gpsfault','sd1_v1_pis_pistransmission_gpsfault_speedsignalfault','sd1_v1_pis_pistransmission_gpslocation_directionoflatitude','sd1_v1_pis_pistransmission_gpslocation_directionoflongitude','sd1_v1_pis_pistransmission_gpslocation_latitudedegrees','sd1_v1_pis_pistransmission_gpslocation_latitudeminutes','sd1_v1_pis_pistransmission_gpslocation_longitudedegrees','sd1_v1_pis_pistransmission_gpslocation_longitudeminutes','sd1_v1_pis_pistransmission_speed_speed','sd1_v1_pis_pistransmission_stationcodeofthecurrentstation_stationcodeofthecurrentstation','sd1_v1_pis_pistransmission_stationcodeofthedestination_stationcodeofthedestination','sd1_v1_pis_pistransmission_stationcodeoftheorigin_stationcodeoftheorigin','sd1_v1_pis_pistransmission_trainid_trainid','sd1_v1_pis_pistransmission_trainstatus_couplingswstatus','sd1_v1_screendisplaydata_doordisplaydataanotherunit_cabdooropen_cardpt1_leftdoor','sd1_v1_screendisplaydata_doordisplaydataanotherunit_cabdooropen_cardpt1_rightdoor','sd1_v1_screendisplaydata_driverscreendataanotherunit_bcufaultdpt1','sd1_v1_screendisplaydata_driverscreendataanotherunit_bcupowersupplydpt1','sd1_v1_toilet_toilettransmission_status_freshwaterlevelsensor25percent_freshwaterlevelsensor25percent','sd1_v1_toilet_toilettransmission_status_wastewaterlevelsensor80percent_wastewaterlevelsensor80percent','sd1_v1_toilet_toilettransmission_status_wcoutofservice_doorlockedbystaff','sd1_v1_toilet_toilettransmission_status_wcoutofservice_freshwatertankempty','sd1_v1_toilet_toilettransmission_status_wcoutofservice_wastewatertankfull','sd1_v1_toilet_toilettransmission_status_wcoutofservice_wcbowlfull','sd1_v1_toilet_toilettransmission_status_wcoutofservice_wcbowloutofservice','sd1_v2_aps_apstransmission_equipmentfailureinformation4_acgr','sd1_v2_aps_apstransmission_equipmentfailureinformation4_dcgr','sd1_v2_aps_apstransmission_equipmentfailureinformation5_bskf','sd1_v2_aps_apstransmission_overheadlinevoltageac_overheadlinevoltageac','sd1_v2_bcu_bcutransmission_analogdata7_bsrpressure','sd1_v2_bcu_bcutransmission_brakefault_bcumajorfault','sd1_v2_bcu_bcutransmission_brakefault_dumpvaluefault1','sd1_v2_bcu_bcutransmission_brakefault_dumpvaluefault2','sd1_v2_bcu_bcutransmission_brakefault_dumpvaluefault3','sd1_v2_bcu_bcutransmission_brakefault_dumpvaluefault4','sd1_v2_bcu_bcutransmission_brakefault_lockedaxle1','sd1_v2_bcu_bcutransmission_brakefault_lockedaxle2','sd1_v2_bcu_bcutransmission_brakefault_lockedaxle3','sd1_v2_bcu_bcutransmission_brakefault_lockedaxle4','sd1_v2_bcu_bcutransmission_brakefault_sandrequestrefused','sd1_v2_bcu_bcutransmission_brakefault_speedsensorfault1','sd1_v2_bcu_bcutransmission_brakefault_speedsensorfault2','sd1_v2_bcu_bcutransmission_brakefault_speedsensorfault3','sd1_v2_bcu_bcutransmission_brakefault_speedsensorfault4','sd1_v2_bcu_bcutransmission_brakefault_wspmajorfault','sd1_v2_bcu_bcutransmission_brakefault_wsptimeout1','sd1_v2_bcu_bcutransmission_brakefault_wsptimeout2','sd1_v2_bcu_bcutransmission_brakefault_wsptimeout3','sd1_v2_bcu_bcutransmission_brakefault_wsptimeout4','sd1_v2_bcu_bcutransmission_brakestatus_sanding','sd1_v2_bcu_bcutransmission_tmscarnumber_tmscarnumber','sd1_v2_dido_dido_monitoringdi110v_buslineearthing1','sd1_v2_dido_dido_monitoringdi110v_buslineearthing2','sd1_v2_dido_dido_monitoringdi110v_powersupplyforairconditioningequipment','sd1_v2_dido_dido_monitoringdi110v_powersupplyforaps','sd1_v2_dido_dido_monitoringdi110v_powersupplyforbrakeequipment','sd1_v2_dido_dido_monitoringdi110v_powersupplyforhottemparatureofaxlebearingdetectionhabdcircuit','sd1_v2_dido_dido_monitoringdi110v_powersupplyfortractionconverter','sd1_v2_dido_dido_monitoringdi24v_anyotherareadetectionisisolated','sd1_v2_dido_dido_monitoringdi24v_brakecockisbeingblocked','sd1_v2_dido_dido_monitoringdi24v_brakeisdragging','sd1_v2_dido_dido_monitoringdi24v_emergencydoorhandle1','sd1_v2_dido_dido_monitoringdi24v_emergencydoorhandle2','sd1_v2_dido_dido_monitoringdi24v_emergencydoorhandle3','sd1_v2_dido_dido_monitoringdi24v_emergencydoorhandle4','sd1_v2_dido_dido_monitoringdi24v_failureofbrakeequipment','sd1_v2_dido_dido_monitoringdi24v_failureofgangwaydoor1','sd1_v2_dido_dido_monitoringdi24v_failureofgangwaydoor2','sd1_v2_dido_dido_monitoringdi24v_firedetectionsystemfailure','sd1_v2_dido_dido_monitoringdi24v_hotaxlebearingdetection11','sd1_v2_dido_dido_monitoringdi24v_hotaxlebearingdetection12','sd1_v2_dido_dido_monitoringdi24v_hotaxlebearingdetection13','sd1_v2_dido_dido_monitoringdi24v_hotaxlebearingdetection14','sd1_v2_dido_dido_monitoringdi24v_hotaxlebearingdetection21','sd1_v2_dido_dido_monitoringdi24v_hotaxlebearingdetection22','sd1_v2_dido_dido_monitoringdi24v_hotaxlebearingdetection23','sd1_v2_dido_dido_monitoringdi24v_hotaxlebearingdetection24','sd1_v2_dido_dido_monitoringdi24v_parkingbrake','sd1_v2_dido_dido_monitoringdi24v_saloonareafire','sd1_v2_dido_dido_monitoringdi24v_tractionareadetectionfunctionfailure','sd1_v2_dido_dido_monitoringdi24v_tractionareadetectionfunctionisisolated','sd1_v2_dido_dido_monitoringdi24v_tractionareafire','sd1_v2_dido_dido_monitoringdi24v_tractionconverterfailure','sd1_v2_screendisplaydata_driverscreendataanotherunit_bcufaultms1','sd1_v2_screendisplaydata_driverscreendataanotherunit_bcupowersupplyms1','sd1_v2_screendisplaydata_driverscreendataanotherunit_tractionfaultms1','sd1_v2_screendisplaydata_driverscreendataanotherunit_tractionisolationms1','sd1_v2_screendisplaydata_driverscreendataanotherunit_tractionmotortorque','sd1_v2_screendisplaydata_driverscreendataanotherunit_tractionpowersupplyms1','sd1_v2_traction_tractiontransmission_analoginformation10_igbttemperatureinconverter','sd1_v2_traction_tractiontransmission_analoginformation11_thermistortemperatureininverter','sd1_v2_traction_tractiontransmission_analoginformation12_igbttemperatureininverter','sd1_v2_traction_tractiontransmission_analoginformation13_thermistortemperatureinbrakechopper','sd1_v2_traction_tractiontransmission_analoginformation14_temperatureriseofbrakeresistor','sd1_v2_traction_tractiontransmission_analoginformation30_overheadlinevoltageac','sd1_v2_traction_tractiontransmission_analoginformation31_overheadlinevoltagedc','sd1_v2_traction_tractiontransmission_analoginformation32_overheadlinecurrentdc','sd1_v2_traction_tractiontransmission_analoginformation36_dclineoverheadlinecurrentlimitvalue','sd1_v2_traction_tractiontransmission_analoginformation38_motorcurrent','sd1_v2_traction_tractiontransmission_analoginformation9_thermistortemperatureinconverter','sd1_v2_traction_tractiontransmission_protectivedetectionsignal1_cfdc','sd1_v2_traction_tractiontransmission_protectivedetectionsignal6_lb3f','sd1_v3_aps_apstransmission_equipmentfailureinformation4_acgr','sd1_v3_aps_apstransmission_equipmentfailureinformation4_dcgr','sd1_v3_aps_apstransmission_equipmentfailureinformation5_bskf','sd1_v3_aps_apstransmission_overheadlinevoltageac_overheadlinevoltageac','sd1_v3_bcu_bcutransmission_analogdata7_bsrpressure','sd1_v3_bcu_bcutransmission_brakefault_bcumajorfault','sd1_v3_bcu_bcutransmission_brakefault_dumpvaluefault1','sd1_v3_bcu_bcutransmission_brakefault_dumpvaluefault2','sd1_v3_bcu_bcutransmission_brakefault_dumpvaluefault3','sd1_v3_bcu_bcutransmission_brakefault_dumpvaluefault4','sd1_v3_bcu_bcutransmission_brakefault_lockedaxle1','sd1_v3_bcu_bcutransmission_brakefault_lockedaxle2','sd1_v3_bcu_bcutransmission_brakefault_lockedaxle3','sd1_v3_bcu_bcutransmission_brakefault_lockedaxle4','sd1_v3_bcu_bcutransmission_brakefault_sandrequestrefused','sd1_v3_bcu_bcutransmission_brakefault_speedsensorfault1','sd1_v3_bcu_bcutransmission_brakefault_speedsensorfault2','sd1_v3_bcu_bcutransmission_brakefault_speedsensorfault3','sd1_v3_bcu_bcutransmission_brakefault_speedsensorfault4','sd1_v3_bcu_bcutransmission_brakefault_wspmajorfault','sd1_v3_bcu_bcutransmission_brakefault_wsptimeout1','sd1_v3_bcu_bcutransmission_brakefault_wsptimeout2','sd1_v3_bcu_bcutransmission_brakefault_wsptimeout3','sd1_v3_bcu_bcutransmission_brakefault_wsptimeout4','sd1_v3_bcu_bcutransmission_brakestatus_sanding','sd1_v3_bcu_bcutransmission_tmscarnumber_tmscarnumber','sd1_v3_dido_dido_monitoringdi110v_busline750vearthingcircuit','sd1_v3_dido_dido_monitoringdi110v_buslineearthing1','sd1_v3_dido_dido_monitoringdi110v_buslineearthing2','sd1_v3_dido_dido_monitoringdi110v_powersupplyforairconditioningequipment','sd1_v3_dido_dido_monitoringdi110v_powersupplyforaps','sd1_v3_dido_dido_monitoringdi110v_powersupplyforbrakeequipment','sd1_v3_dido_dido_monitoringdi110v_powersupplyforhottemparatureofaxlebearingdetectionhabdcircuit','sd1_v3_dido_dido_monitoringdi110v_powersupplyfortractionconverter','sd1_v3_dido_dido_monitoringdi24v_anyotherareadetectionisisolated','sd1_v3_dido_dido_monitoringdi24v_apsfailure','sd1_v3_dido_dido_monitoringdi24v_brakecockisbeingblocked','sd1_v3_dido_dido_monitoringdi24v_brakeisdragging','sd1_v3_dido_dido_monitoringdi24v_emergencydoorhandle1','sd1_v3_dido_dido_monitoringdi24v_emergencydoorhandle2','sd1_v3_dido_dido_monitoringdi24v_emergencydoorhandle3','sd1_v3_dido_dido_monitoringdi24v_emergencydoorhandle4','sd1_v3_dido_dido_monitoringdi24v_failureofbrakeequipment','sd1_v3_dido_dido_monitoringdi24v_failureofgangwaydoor1','sd1_v3_dido_dido_monitoringdi24v_failureofgangwaydoor2','sd1_v3_dido_dido_monitoringdi24v_firedetectionsystemfailure','sd1_v3_dido_dido_monitoringdi24v_hotaxlebearingdetection11','sd1_v3_dido_dido_monitoringdi24v_hotaxlebearingdetection12','sd1_v3_dido_dido_monitoringdi24v_hotaxlebearingdetection13','sd1_v3_dido_dido_monitoringdi24v_hotaxlebearingdetection14','sd1_v3_dido_dido_monitoringdi24v_hotaxlebearingdetection21','sd1_v3_dido_dido_monitoringdi24v_hotaxlebearingdetection22','sd1_v3_dido_dido_monitoringdi24v_hotaxlebearingdetection23','sd1_v3_dido_dido_monitoringdi24v_hotaxlebearingdetection24','sd1_v3_dido_dido_monitoringdi24v_parkingbrake','sd1_v3_dido_dido_monitoringdi24v_saloonareafire','sd1_v3_dido_dido_monitoringdi24v_tractionareadetectionfunctionfailure','sd1_v3_dido_dido_monitoringdi24v_tractionareadetectionfunctionisisolated','sd1_v3_dido_dido_monitoringdi24v_tractionareafire','sd1_v3_dido_dido_monitoringdi24v_tractionconverterfailure','sd1_v3_screendisplaydata_driverscreendataanotherunit_bcufaultms2','sd1_v3_screendisplaydata_driverscreendataanotherunit_bcupowersupplyms2','sd1_v3_screendisplaydata_driverscreendataanotherunit_tractionfaultms2','sd1_v3_screendisplaydata_driverscreendataanotherunit_tractionisolationms2','sd1_v3_screendisplaydata_driverscreendataanotherunit_tractionmotortorque','sd1_v3_screendisplaydata_driverscreendataanotherunit_tractionpowersupplyms2','sd1_v3_traction_tractiontransmission_analoginformation10_igbttemperatureinconverter','sd1_v3_traction_tractiontransmission_analoginformation11_thermistortemperatureininverter','sd1_v3_traction_tractiontransmission_analoginformation12_igbttemperatureininverter','sd1_v3_traction_tractiontransmission_analoginformation13_thermistortemperatureinbrakechopper','sd1_v3_traction_tractiontransmission_analoginformation14_temperatureriseofbrakeresistor','sd1_v3_traction_tractiontransmission_analoginformation30_overheadlinevoltageac','sd1_v3_traction_tractiontransmission_analoginformation31_overheadlinevoltagedc','sd1_v3_traction_tractiontransmission_analoginformation32_overheadlinecurrentdc','sd1_v3_traction_tractiontransmission_analoginformation36_dclineoverheadlinecurrentlimitvalue','sd1_v3_traction_tractiontransmission_analoginformation38_motorcurrent','sd1_v3_traction_tractiontransmission_analoginformation9_thermistortemperatureinconverter','sd1_v3_traction_tractiontransmission_protectivedetectionsignal1_cfdc','sd1_v3_traction_tractiontransmission_protectivedetectionsignal6_lb3f','sd1_v4_bcu_bcutransmission_analogdata7_bsrpressure','sd1_v4_bcu_bcutransmission_brakefault_bcumajorfault','sd1_v4_bcu_bcutransmission_brakefault_dumpvaluefault1','sd1_v4_bcu_bcutransmission_brakefault_dumpvaluefault2','sd1_v4_bcu_bcutransmission_brakefault_dumpvaluefault3','sd1_v4_bcu_bcutransmission_brakefault_dumpvaluefault4','sd1_v4_bcu_bcutransmission_brakefault_lockedaxle1','sd1_v4_bcu_bcutransmission_brakefault_lockedaxle2','sd1_v4_bcu_bcutransmission_brakefault_lockedaxle3','sd1_v4_bcu_bcutransmission_brakefault_lockedaxle4','sd1_v4_bcu_bcutransmission_brakefault_sandrequestrefused','sd1_v4_bcu_bcutransmission_brakefault_speedsensorfault1','sd1_v4_bcu_bcutransmission_brakefault_speedsensorfault2','sd1_v4_bcu_bcutransmission_brakefault_speedsensorfault3','sd1_v4_bcu_bcutransmission_brakefault_speedsensorfault4','sd1_v4_bcu_bcutransmission_brakefault_wspmajorfault','sd1_v4_bcu_bcutransmission_brakefault_wsptimeout1','sd1_v4_bcu_bcutransmission_brakefault_wsptimeout2','sd1_v4_bcu_bcutransmission_brakefault_wsptimeout3','sd1_v4_bcu_bcutransmission_brakefault_wsptimeout4','sd1_v4_bcu_bcutransmission_brakestatus_sanding','sd1_v4_bcu_bcutransmission_tmscarnumber_tmscarnumber','sd1_v4_dido_dido_monitoringdi110v_buslineearthing1','sd1_v4_dido_dido_monitoringdi110v_buslineearthing2','sd1_v4_dido_dido_monitoringdi110v_powersupplyforairconditioningequipment','sd1_v4_dido_dido_monitoringdi110v_powersupplyforbrakeequipment','sd1_v4_dido_dido_monitoringdi110v_powersupplyforhottemparatureofaxlebearingdetectionhabdcircuit','sd1_v4_dido_dido_monitoringdi110v_powersupplyfortractionconverter','sd1_v4_dido_dido_monitoringdi24v_anyotherareadetectionisisolated','sd1_v4_dido_dido_monitoringdi24v_brakecockisbeingblocked','sd1_v4_dido_dido_monitoringdi24v_brakeisdragging','sd1_v4_dido_dido_monitoringdi24v_emergencydoorhandle1','sd1_v4_dido_dido_monitoringdi24v_emergencydoorhandle2','sd1_v4_dido_dido_monitoringdi24v_emergencydoorhandle3','sd1_v4_dido_dido_monitoringdi24v_emergencydoorhandle4','sd1_v4_dido_dido_monitoringdi24v_failureofbrakeequipment','sd1_v4_dido_dido_monitoringdi24v_failureofgangwaydoor1','sd1_v4_dido_dido_monitoringdi24v_failureofgangwaydoor2','sd1_v4_dido_dido_monitoringdi24v_firedetectionsystemfailure','sd1_v4_dido_dido_monitoringdi24v_hotaxlebearingdetection11','sd1_v4_dido_dido_monitoringdi24v_hotaxlebearingdetection12','sd1_v4_dido_dido_monitoringdi24v_hotaxlebearingdetection13','sd1_v4_dido_dido_monitoringdi24v_hotaxlebearingdetection14','sd1_v4_dido_dido_monitoringdi24v_hotaxlebearingdetection21','sd1_v4_dido_dido_monitoringdi24v_hotaxlebearingdetection22','sd1_v4_dido_dido_monitoringdi24v_hotaxlebearingdetection23','sd1_v4_dido_dido_monitoringdi24v_hotaxlebearingdetection24','sd1_v4_dido_dido_monitoringdi24v_parkingbrake','sd1_v4_dido_dido_monitoringdi24v_saloonareafire','sd1_v4_dido_dido_monitoringdi24v_tractionareadetectionfunctionfailure','sd1_v4_dido_dido_monitoringdi24v_tractionareadetectionfunctionisisolated','sd1_v4_dido_dido_monitoringdi24v_tractionareafire','sd1_v4_dido_dido_monitoringdi24v_tractionconverterfailure','sd1_v4_screendisplaydata_driverscreendataanotherunit_bcufaultms3','sd1_v4_screendisplaydata_driverscreendataanotherunit_bcupowersupplyms3','sd1_v4_screendisplaydata_driverscreendataanotherunit_tractionfaultms3','sd1_v4_screendisplaydata_driverscreendataanotherunit_tractionisolationms3','sd1_v4_screendisplaydata_driverscreendataanotherunit_tractionmotortorque','sd1_v4_screendisplaydata_driverscreendataanotherunit_tractionpowersupplyms3','sd1_v4_traction_tractiontransmission_analoginformation10_igbttemperatureinconverter','sd1_v4_traction_tractiontransmission_analoginformation11_thermistortemperatureininverter','sd1_v4_traction_tractiontransmission_analoginformation12_igbttemperatureininverter','sd1_v4_traction_tractiontransmission_analoginformation13_thermistortemperatureinbrakechopper','sd1_v4_traction_tractiontransmission_analoginformation14_temperatureriseofbrakeresistor','sd1_v4_traction_tractiontransmission_analoginformation30_overheadlinevoltageac','sd1_v4_traction_tractiontransmission_analoginformation31_overheadlinevoltagedc','sd1_v4_traction_tractiontransmission_analoginformation32_overheadlinecurrentdc','sd1_v4_traction_tractiontransmission_analoginformation36_dclineoverheadlinecurrentlimitvalue','sd1_v4_traction_tractiontransmission_analoginformation38_motorcurrent','sd1_v4_traction_tractiontransmission_analoginformation9_thermistortemperatureinconverter','sd1_v4_traction_tractiontransmission_protectivedetectionsignal1_cfdc','sd1_v4_traction_tractiontransmission_protectivedetectionsignal6_lb3f','sd1_v5_aps_apstransmission_equipmentfailureinformation4_acgr','sd1_v5_aps_apstransmission_equipmentfailureinformation4_dcgr','sd1_v5_aps_apstransmission_equipmentfailureinformation5_bskf','sd1_v5_aps_apstransmission_overheadlinevoltageac_overheadlinevoltageac','sd1_v5_bcu_bcutransmission_analogdata7_bsrpressure','sd1_v5_bcu_bcutransmission_brakefault_bcumajorfault','sd1_v5_bcu_bcutransmission_brakefault_dumpvaluefault1','sd1_v5_bcu_bcutransmission_brakefault_dumpvaluefault2','sd1_v5_bcu_bcutransmission_brakefault_dumpvaluefault3','sd1_v5_bcu_bcutransmission_brakefault_dumpvaluefault4','sd1_v5_bcu_bcutransmission_brakefault_lockedaxle1','sd1_v5_bcu_bcutransmission_brakefault_lockedaxle2','sd1_v5_bcu_bcutransmission_brakefault_lockedaxle3','sd1_v5_bcu_bcutransmission_brakefault_lockedaxle4','sd1_v5_bcu_bcutransmission_brakefault_sandrequestrefused','sd1_v5_bcu_bcutransmission_brakefault_speedsensorfault1','sd1_v5_bcu_bcutransmission_brakefault_speedsensorfault2','sd1_v5_bcu_bcutransmission_brakefault_speedsensorfault3','sd1_v5_bcu_bcutransmission_brakefault_speedsensorfault4','sd1_v5_bcu_bcutransmission_brakefault_wspmajorfault','sd1_v5_bcu_bcutransmission_brakefault_wsptimeout1','sd1_v5_bcu_bcutransmission_brakefault_wsptimeout2','sd1_v5_bcu_bcutransmission_brakefault_wsptimeout3','sd1_v5_bcu_bcutransmission_brakefault_wsptimeout4','sd1_v5_bcu_bcutransmission_brakestatus_sanding','sd1_v5_bcu_bcutransmission_tmscarnumber_tmscarnumber','sd1_v5_dido_dido_monitoringdi110v_buslineearthing1','sd1_v5_dido_dido_monitoringdi110v_buslineearthing2','sd1_v5_dido_dido_monitoringdi110v_powersupplyforairconditioningequipment','sd1_v5_dido_dido_monitoringdi110v_powersupplyforaps','sd1_v5_dido_dido_monitoringdi110v_powersupplyforbrakeequipment','sd1_v5_dido_dido_monitoringdi110v_powersupplyforhottemparatureofaxlebearingdetectionhabdcircuit','sd1_v5_dido_dido_monitoringdi110v_powersupplyfortractionconverter','sd1_v5_dido_dido_monitoringdi24v_anyotherareadetectionisisolated','sd1_v5_dido_dido_monitoringdi24v_brakecockisbeingblocked','sd1_v5_dido_dido_monitoringdi24v_brakeisdragging','sd1_v5_dido_dido_monitoringdi24v_emergencydoorhandle1','sd1_v5_dido_dido_monitoringdi24v_emergencydoorhandle2','sd1_v5_dido_dido_monitoringdi24v_emergencydoorhandle3','sd1_v5_dido_dido_monitoringdi24v_emergencydoorhandle4','sd1_v5_dido_dido_monitoringdi24v_failureofbrakeequipment','sd1_v5_dido_dido_monitoringdi24v_failureofgangwaydoor1','sd1_v5_dido_dido_monitoringdi24v_failureofgangwaydoor2','sd1_v5_dido_dido_monitoringdi24v_firedetectionsystemfailure','sd1_v5_dido_dido_monitoringdi24v_hotaxlebearingdetection11','sd1_v5_dido_dido_monitoringdi24v_hotaxlebearingdetection12','sd1_v5_dido_dido_monitoringdi24v_hotaxlebearingdetection13','sd1_v5_dido_dido_monitoringdi24v_hotaxlebearingdetection14','sd1_v5_dido_dido_monitoringdi24v_hotaxlebearingdetection21','sd1_v5_dido_dido_monitoringdi24v_hotaxlebearingdetection22','sd1_v5_dido_dido_monitoringdi24v_hotaxlebearingdetection23','sd1_v5_dido_dido_monitoringdi24v_hotaxlebearingdetection24','sd1_v5_dido_dido_monitoringdi24v_parkingbrake','sd1_v5_dido_dido_monitoringdi24v_saloonareafire','sd1_v5_dido_dido_monitoringdi24v_tractionareadetectionfunctionfailure','sd1_v5_dido_dido_monitoringdi24v_tractionareadetectionfunctionisisolated','sd1_v5_dido_dido_monitoringdi24v_tractionareafire','sd1_v5_dido_dido_monitoringdi24v_tractionconverterfailure','sd1_v5_screendisplaydata_driverscreendataanotherunit_bcufaultms4','sd1_v5_screendisplaydata_driverscreendataanotherunit_bcupowersupplyms4','sd1_v5_screendisplaydata_driverscreendataanotherunit_tractionfaultms4','sd1_v5_screendisplaydata_driverscreendataanotherunit_tractionisolationms4','sd1_v5_screendisplaydata_driverscreendataanotherunit_tractionmotortorque','sd1_v5_screendisplaydata_driverscreendataanotherunit_tractionpowersupplyms4','sd1_v5_traction_tractiontransmission_analoginformation10_igbttemperatureinconverter','sd1_v5_traction_tractiontransmission_analoginformation11_thermistortemperatureininverter','sd1_v5_traction_tractiontransmission_analoginformation12_igbttemperatureininverter','sd1_v5_traction_tractiontransmission_analoginformation13_thermistortemperatureinbrakechopper','sd1_v5_traction_tractiontransmission_analoginformation14_temperatureriseofbrakeresistor','sd1_v5_traction_tractiontransmission_analoginformation30_overheadlinevoltageac','sd1_v5_traction_tractiontransmission_analoginformation31_overheadlinevoltagedc','sd1_v5_traction_tractiontransmission_analoginformation32_overheadlinecurrentdc','sd1_v5_traction_tractiontransmission_analoginformation36_dclineoverheadlinecurrentlimitvalue','sd1_v5_traction_tractiontransmission_analoginformation38_motorcurrent','sd1_v5_traction_tractiontransmission_analoginformation9_thermistortemperatureinconverter','sd1_v5_traction_tractiontransmission_protectivedetectionsignal1_cfdc','sd1_v5_traction_tractiontransmission_protectivedetectionsignal6_lb3f','sd1_v6_bcu_bcutransmission_analogdata7_bsrpressure','sd1_v6_bcu_bcutransmission_brakefault_bcumajorfault','sd1_v6_bcu_bcutransmission_brakefault_dumpvaluefault1','sd1_v6_bcu_bcutransmission_brakefault_dumpvaluefault2','sd1_v6_bcu_bcutransmission_brakefault_dumpvaluefault3','sd1_v6_bcu_bcutransmission_brakefault_dumpvaluefault4','sd1_v6_bcu_bcutransmission_brakefault_lockedaxle1','sd1_v6_bcu_bcutransmission_brakefault_lockedaxle2','sd1_v6_bcu_bcutransmission_brakefault_lockedaxle3','sd1_v6_bcu_bcutransmission_brakefault_lockedaxle4','sd1_v6_bcu_bcutransmission_brakefault_sandrequestrefused','sd1_v6_bcu_bcutransmission_brakefault_speedsensorfault1','sd1_v6_bcu_bcutransmission_brakefault_speedsensorfault2','sd1_v6_bcu_bcutransmission_brakefault_speedsensorfault3','sd1_v6_bcu_bcutransmission_brakefault_speedsensorfault4','sd1_v6_bcu_bcutransmission_brakefault_wspmajorfault','sd1_v6_bcu_bcutransmission_brakefault_wsptimeout1','sd1_v6_bcu_bcutransmission_brakefault_wsptimeout2','sd1_v6_bcu_bcutransmission_brakefault_wsptimeout3','sd1_v6_bcu_bcutransmission_brakefault_wsptimeout4','sd1_v6_bcu_bcutransmission_brakestatus_sanding','sd1_v6_bcu_bcutransmission_tmscarnumber_tmscarnumber','sd1_v6_dido_dido_fsdi_ctrlacmode','sd1_v6_dido_dido_fsdi_doorclosecommandleft','sd1_v6_dido_dido_fsdi_doorclosecommandright','sd1_v6_dido_dido_fsdi_dooropencommandleft','sd1_v6_dido_dido_fsdi_dooropencommandright','sd1_v6_dido_dido_fsdi_doorreleaseleft','sd1_v6_dido_dido_fsdi_doorreleaseright','sd1_v6_dido_dido_fsdi_forwardmodeline','sd1_v6_dido_dido_fsdi_reversemodeline','sd1_v6_dido_dido_fsdi_speedsignalmorethan25kmh','sd1_v6_dido_dido_fsdi_speedsignalmorethan5kmh','sd1_v6_dido_dido_fsdo_tmsfailure','sd1_v6_dido_dido_monitoringdi110v_couplercoverclosingswitch','sd1_v6_dido_dido_monitoringdi110v_couplercoveropeningswitch','sd1_v6_dido_dido_monitoringdi110v_couplingsw','sd1_v6_dido_dido_monitoringdi110v_dcmode','sd1_v6_dido_dido_monitoringdi110v_ddson','sd1_v6_dido_dido_monitoringdi110v_electriccouplerisolationsw','sd1_v6_dido_dido_monitoringdi110v_emergencypantographup','sd1_v6_dido_dido_monitoringdi110v_networkrailacmode','sd1_v6_dido_dido_monitoringdi110v_otmrfailure','sd1_v6_dido_dido_monitoringdi110v_pantographdownshoeupsw','sd1_v6_dido_dido_monitoringdi110v_pantographupshoedownsw','sd1_v6_dido_dido_monitoringdi110v_poweringcommand','sd1_v6_dido_dido_monitoringdi110v_powersupplyforaxletemperaturedetectioncircuit','sd1_v6_dido_dido_monitoringdi110v_powersupplyforbrake','sd1_v6_dido_dido_monitoringdi110v_powersupplyfordriversdisplayunit','sd1_v6_dido_dido_monitoringdi110v_powersupplyforhvac','sd1_v6_dido_dido_monitoringdi110v_powersupplyforotmr','sd1_v6_dido_dido_monitoringdi110v_speedindicatorfailure','sd1_v6_dido_dido_monitoringdi110v_uncouplingsw','sd1_v6_dido_dido_monitoringdi110v_vcb','sd1_v6_dido_dido_monitoringdi24v_acpowersupplyisovercurrentacocrstatus','sd1_v6_dido_dido_monitoringdi24v_anyotherareadetectionisisolated','sd1_v6_dido_dido_monitoringdi24v_auxliarycompressorisinoperation','sd1_v6_dido_dido_monitoringdi24v_brakecockisbeingblocked','sd1_v6_dido_dido_monitoringdi24v_brakeisdragging','sd1_v6_dido_dido_monitoringdi24v_cabareafire','sd1_v6_dido_dido_monitoringdi24v_compressorfailure','sd1_v6_dido_dido_monitoringdi24v_emergencydoorhandle1','sd1_v6_dido_dido_monitoringdi24v_emergencydoorhandle2','sd1_v6_dido_dido_monitoringdi24v_emergencydoorhandle3','sd1_v6_dido_dido_monitoringdi24v_emergencydoorhandle4','sd1_v6_dido_dido_monitoringdi24v_failureofbrake','sd1_v6_dido_dido_monitoringdi24v_failureofgangwaydoor','sd1_v6_dido_dido_monitoringdi24v_firedetectionsystemfailure','sd1_v6_dido_dido_monitoringdi24v_frontcoverclosestatus','sd1_v6_dido_dido_monitoringdi24v_frontcoveropenstatus','sd1_v6_dido_dido_monitoringdi24v_hotaxlebearingdetection11','sd1_v6_dido_dido_monitoringdi24v_hotaxlebearingdetection12','sd1_v6_dido_dido_monitoringdi24v_hotaxlebearingdetection13','sd1_v6_dido_dido_monitoringdi24v_hotaxlebearingdetection14','sd1_v6_dido_dido_monitoringdi24v_hotaxlebearingdetection21','sd1_v6_dido_dido_monitoringdi24v_hotaxlebearingdetection22','sd1_v6_dido_dido_monitoringdi24v_hotaxlebearingdetection23','sd1_v6_dido_dido_monitoringdi24v_hotaxlebearingdetection24','sd1_v6_dido_dido_monitoringdi24v_kvbemergencybrake','sd1_v6_dido_dido_monitoringdi24v_pantographautomaticdowndetection','sd1_v6_dido_dido_monitoringdi24v_pantographstatus','sd1_v6_dido_dido_monitoringdi24v_parkingbrake','sd1_v6_dido_dido_monitoringdi24v_powersupplyforavacuumequipmentfortoiletsystem','sd1_v6_dido_dido_monitoringdi24v_saloonareafire','sd1_v6_dido_dido_monitoringdi24v_sandingcockisbeingblocked','sd1_v6_dido_dido_monitoringdi24v_toiletareafire','sd1_v6_dido_dido_monitoringdi24v_tpwsawsemergencybrake','sd1_v6_dido_dido_monitoringdi24v_tractionabnormaldetectionfunctionisfailed','sd1_v6_dido_dido_monitoringdi24v_tractionareafire','sd1_v6_dido_dido_monitoringdi24v_tractionarealdetectionfunctionisisolated','sd1_v6_dido_dido_monitoringdi24v_tvm430emergencybrake','sd1_v6_dido_dido_monitoringdi24v_warninghornisisolated','sd1_v6_dido_dido_monitoringdo_powersupplyforbuzzerfordriversdispalyunit','sd1_v6_dido_dido_monitoringdo_slipandskiddetectingindicatorlampincab','sd1_v6_hvac_hvactransmission_airconditioningequipmentmonitorinformation9_cabtemperature','sd1_v6_otmr_otmrtransmission_brake_brakecylinderpressuredpts1','sd1_v6_otmr_otmrtransmission_brake_brakecylinderpressuredpts2','sd1_v6_otmr_otmrtransmission_brake_brakecylinderpressurems1','sd1_v6_otmr_otmrtransmission_brake_brakecylinderpressurems2','sd1_v6_otmr_otmrtransmission_brake_brakecylinderpressurems3','sd1_v6_otmr_otmrtransmission_brake_brakecylinderpressurems4','sd1_v6_otmr_otmrtransmission_brake_brakereservoirpressuredpts1','sd1_v6_otmr_otmrtransmission_brake_brakereservoirpressuredpts2','sd1_v6_otmr_otmrtransmission_brake_brakereservoirpressurems1','sd1_v6_otmr_otmrtransmission_brake_brakereservoirpressurems2','sd1_v6_otmr_otmrtransmission_brake_brakereservoirpressurems3','sd1_v6_otmr_otmrtransmission_brake_brakereservoirpressurems4','sd1_v6_otmr_otmrtransmission_brake_wspactivedpts1','sd1_v6_otmr_otmrtransmission_brake_wspactivedpts2','sd1_v6_otmr_otmrtransmission_brake_wspactivems1','sd1_v6_otmr_otmrtransmission_brake_wspactivems2','sd1_v6_otmr_otmrtransmission_brake_wspactivems3','sd1_v6_otmr_otmrtransmission_brake_wspactivems4','sd1_v6_otmr_otmrtransmission_couple_cabcoupled','sd1_v6_otmr_otmrtransmission_couple_couplecoverswitch','sd1_v6_otmr_otmrtransmission_couple_couplepushbutton','sd1_v6_otmr_otmrtransmission_couple_uncouplepushbutton','sd1_v6_otmr_otmrtransmission_door_dirinformation1','sd1_v6_otmr_otmrtransmission_door_dirinformation12','sd1_v6_otmr_otmrtransmission_door_dirinformation6','sd1_v6_otmr_otmrtransmission_door_dirinformation7','sd1_v6_otmr_otmrtransmission_lineinformation_ctrlacselectbutton','sd1_v6_otmr_otmrtransmission_lineinformation_nracselectbutton','sd1_v6_otmr_otmrtransmission_lineinformation_nrdcselectbutton','sd1_v6_otmr_otmrtransmission_pea_peaoperationdpts1','sd1_v6_otmr_otmrtransmission_pea_peaoperationdpts2','sd1_v6_otmr_otmrtransmission_pea_peaoperationms1','sd1_v6_otmr_otmrtransmission_pea_peaoperationms2','sd1_v6_otmr_otmrtransmission_pea_peaoperationms3','sd1_v6_otmr_otmrtransmission_pea_peaoperationms4','sd1_v6_otmr_otmrtransmission_sanding_sandercontroldpst1','sd1_v6_otmr_otmrtransmission_sanding_sandercontroldpts2','sd1_v6_otmr_otmrtransmission_sanding_sandercontrolms1','sd1_v6_otmr_otmrtransmission_sanding_sandercontrolms2','sd1_v6_otmr_otmrtransmission_sanding_sandercontrolms3','sd1_v6_otmr_otmrtransmission_sanding_sandercontrolms4','sd1_v6_otmr_otmrtransmission_sanding_sandrequestrefuseddpst1','sd1_v6_otmr_otmrtransmission_sanding_sandrequestrefuseddpts2','sd1_v6_otmr_otmrtransmission_sanding_sandrequestrefusedms1','sd1_v6_otmr_otmrtransmission_sanding_sandrequestrefusedms2','sd1_v6_otmr_otmrtransmission_sanding_sandrequestrefusedms3','sd1_v6_otmr_otmrtransmission_sanding_sandrequestrefusedms4','sd1_v6_otmr_otmrtransmission_sdo_emergencyreleaseoperation','sd1_v6_otmr_otmrtransmission_sdo_leftsidedoorsrelease','sd1_v6_otmr_otmrtransmission_sdo_rightsidedoorsrelease','sd1_v6_otmr_otmrtransmission_sdo_sdocommand1','sd1_v6_otmr_otmrtransmission_sdo_sdocommand10','sd1_v6_otmr_otmrtransmission_sdo_sdocommand11','sd1_v6_otmr_otmrtransmission_sdo_sdocommand12','sd1_v6_otmr_otmrtransmission_sdo_sdocommand2','sd1_v6_otmr_otmrtransmission_sdo_sdocommand3','sd1_v6_otmr_otmrtransmission_sdo_sdocommand4','sd1_v6_otmr_otmrtransmission_sdo_sdocommand5','sd1_v6_otmr_otmrtransmission_sdo_sdocommand6','sd1_v6_otmr_otmrtransmission_sdo_sdocommand7','sd1_v6_otmr_otmrtransmission_sdo_sdocommand8','sd1_v6_otmr_otmrtransmission_sdo_sdocommand9','sd1_v6_otmr_otmrtransmission_sdo_sdodoorreleaseerror','sd1_v6_otmr_otmrtransmission_sdo_stationchanged','sd1_v6_otmr_otmrtransmission_sdo_tmssdofault1','sd1_v6_otmr_otmrtransmission_sdo_tmssdofault2','sd1_v6_otmr_otmrtransmission_speedset_speedsetactive','sd1_v6_otmr_otmrtransmission_speedset_speedsetspeed','sd1_v6_otmr_otmrtransmission_speedset_tractionactiveforspeedset','sd1_v6_otmr_otmrtransmission_traction_icemodems1','sd1_v6_otmr_otmrtransmission_traction_icemodems2','sd1_v6_otmr_otmrtransmission_traction_icemodems3','sd1_v6_otmr_otmrtransmission_traction_icemodems4','sd1_v6_otmr_otmrtransmission_traction_poweringmodems1','sd1_v6_otmr_otmrtransmission_traction_poweringmodems2','sd1_v6_otmr_otmrtransmission_traction_poweringmodems3','sd1_v6_otmr_otmrtransmission_traction_poweringmodems4','sd1_v6_otmr_otmrtransmission_traction_powerredistributionmodems1','sd1_v6_otmr_otmrtransmission_traction_powerredistributionmodems2','sd1_v6_otmr_otmrtransmission_traction_powerredistributionmodems3','sd1_v6_otmr_otmrtransmission_traction_powerredistributionmodems4','sd1_v6_otmr_otmrtransmission_traction_slowspeedmodems1','sd1_v6_otmr_otmrtransmission_traction_slowspeedmodems2','sd1_v6_otmr_otmrtransmission_traction_slowspeedmodems3','sd1_v6_otmr_otmrtransmission_traction_slowspeedmodems4','sd1_v6_otmr_otmrtransmission_traction_tractionfaultms1','sd1_v6_otmr_otmrtransmission_traction_tractionfaultms2','sd1_v6_otmr_otmrtransmission_traction_tractionfaultms3','sd1_v6_otmr_otmrtransmission_traction_tractionfaultms4','sd1_v6_otmr_otmrtransmission_traction_tractionwspdetectedms1','sd1_v6_otmr_otmrtransmission_traction_tractionwspdetectedms2','sd1_v6_otmr_otmrtransmission_traction_tractionwspdetectedms3','sd1_v6_otmr_otmrtransmission_traction_tractionwspdetectedms4','sd1_v6_otmr_otmrtransmission_trainfault_trainsystemfaultack','sd1_v6_otmr_otmrtransmission_vcb_vcb1','sd1_v6_otmr_otmrtransmission_vcb_vcb2','sd1_v6_screendisplaydata_doordisplaydataanotherunit_cabdooropen_cardpt2_leftdoor','sd1_v6_screendisplaydata_doordisplaydataanotherunit_cabdooropen_cardpt2_rightdoor','sd1_v6_screendisplaydata_driverscreendataanotherunit_bcufaultdpt2','sd1_v6_screendisplaydata_driverscreendataanotherunit_bcupowersupplydpt2','sd1_v6_toilet_toilettransmission_status_freshwaterlevelsensor25percent_freshwaterlevelsensor25percent','sd1_v6_toilet_toilettransmission_status_wastewaterlevelsensor80percent_wastewaterlevelsensor80percent','sd1_v6_toilet_toilettransmission_status_wcoutofservice_doorlockedbystaff','sd1_v6_toilet_toilettransmission_status_wcoutofservice_dooroutofservice','sd1_v6_toilet_toilettransmission_status_wcoutofservice_failureinautomaticdoor','sd1_v6_toilet_toilettransmission_status_wcoutofservice_freshwatertankempty','sd1_v6_toilet_toilettransmission_status_wcoutofservice_wastewatertankfull','sd1_v6_toilet_toilettransmission_status_wcoutofservice_wcbowlfull','sd1_v6_toilet_toilettransmission_status_wcoutofservice_wcbowloutofservicef']
# test

In [239]:
# df_test = pd.DataFrame(test, columns = ["signal_code"])
# df_test

In [149]:
# df_test.to_excel("signal_need_to_compare.xlsx")

In [430]:
# compare[compare["sd1_v0_eventrecord_eventrecord_traininformation_trainspeed"].isna()]

,unit_no,signal_code,frozen_times,numeric_value,calendar_timestamp,sd1_v0_unitid,sd1_v0_eventrecord_eventrecord_traininformation_trainspeed
3907,800002,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-06-25 08:43:20, 2024-06-25 08:43:20, 202...",148.8,2024-06-25 08:43:22.800,NaN,NaN
7602,800002,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-06-25 08:56:20, 2024-06-25 08:56:20, 202...",0.0,2024-06-25 08:56:23.000,NaN,NaN
11139,800002,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-06-25 09:08:15, 2024-06-25 09:08:15, 202...",61.1,2024-06-25 09:08:16.800,NaN,NaN
15795,800002,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-06-25 09:23:44, 2024-06-25 09:23:45, 202...",144.4,2024-06-25 09:23:48.800,NaN,NaN
16056,800002,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-06-25 09:24:39, 2024-06-25 09:24:40, 202...",41.0,2024-06-25 09:24:41.000,NaN,NaN
17152,800002,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-06-25 09:28:19, 2024-06-25 09:28:20, 202...",0.0,2024-06-25 09:28:20.800,NaN,NaN
17202,800002,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-06-25 09:28:30, 2024-06-25 09:28:30, 202...",0.0,2024-06-25 09:28:30.800,NaN,NaN
17345,800002,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-06-25 09:28:59, 2024-06-25 09:29:00, 202...",0.0,2024-06-25 09:28:59.800,NaN,NaN
17385,800002,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-06-25 09:29:04, 2024-06-25 09:29:05, 202...",4.0,2024-06-25 09:29:07.800,NaN,NaN
17405,800002,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-06-25 09:29:09, 2024-06-25 09:29:10, 202...",4.0,2024-06-25 09:29:11.800,NaN,NaN
17430,800002,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-06-25 09:29:14, 2024-06-25 09:29:15, 202...",4.0,2024-06-25 09:29:16.800,NaN,NaN
17501,800002,sd1_v0_eventrecord_eventrecord_traininformatio...,"[2024-06-25 09:29:29, 2024-06-25 09:29:29, 202...",4.0,2024-06-25 09:29:30.800,NaN,NaN